/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.puntoinflexion.vista;

/**
 *
 * @author damia
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGjPanel = new javax.swing.JPanel();
        BGToolBarjPanel = new javax.swing.JPanel();
        TitleAppjLabel = new javax.swing.JLabel();
        BarBuscarjTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BGBreadCrumjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BGjPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BGTEXTjPanel = new javax.swing.JPanel();
        UNAjLabel10 = new javax.swing.JLabel();
        FUNCIOESjLabel7 = new javax.swing.JLabel();
        YPRECISAjLabel11 = new javax.swing.JLabel();
        PUNTOSjLabel9 = new javax.swing.JLabel();
        ADEMASjLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BGToolBarjPanel1 = new javax.swing.JPanel();
        TitleAppjLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BGjPanel.setBackground(new java.awt.Color(247, 251, 252));
        BGjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGToolBarjPanel.setBackground(new java.awt.Color(42, 157, 143));
        BGToolBarjPanel.setPreferredSize(new java.awt.Dimension(1366, 70));
        BGToolBarjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleAppjLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TitleAppjLabel.setForeground(new java.awt.Color(247, 251, 252));
        TitleAppjLabel.setText("INFLEX POINT");
        TitleAppjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGToolBarjPanel.add(TitleAppjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 70));

        BarBuscarjTextField.setBackground(new java.awt.Color(247, 251, 252));
        BarBuscarjTextField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        BarBuscarjTextField.setText("Buscar");
        BarBuscarjTextField.setPreferredSize(new java.awt.Dimension(300, 30));
        BarBuscarjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarBuscarjTextFieldActionPerformed(evt);
            }
        });
        BGToolBarjPanel.add(BarBuscarjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        BGToolBarjPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 17, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        BGToolBarjPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 17, -1, -1));

        BGjPanel.add(BGToolBarjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BGBreadCrumjPanel.setBackground(new java.awt.Color(38, 70, 83));
        BGBreadCrumjPanel.setPreferredSize(new java.awt.Dimension(1366, 40));
        BGBreadCrumjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("AYUDA");
        BGBreadCrumjPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("INICIO");
        BGBreadCrumjPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("CALCULAR");
        BGBreadCrumjPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("GRÁFICOS");
        BGBreadCrumjPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("CONFIGURACIÓN");
        BGBreadCrumjPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 40));

        BGjPanel.add(BGBreadCrumjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 598));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGjPanel1.setBackground(new java.awt.Color(247, 251, 252));
        BGjPanel1.setPreferredSize(new java.awt.Dimension(1366, 588));
        BGjPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("BIENVENIDO A INFLEXPOINT");
        BGjPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 670, 70));

        BGTEXTjPanel.setBackground(new java.awt.Color(247, 251, 252));
        BGTEXTjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNAjLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UNAjLabel10.setText("Una herramienta diseñada para analizar");
        BGTEXTjPanel.add(UNAjLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 50));

        FUNCIOESjLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        FUNCIOESjLabel7.setText("funciones matemáticas de forma rápida");
        BGTEXTjPanel.add(FUNCIOESjLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 520, 50));

        YPRECISAjLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        YPRECISAjLabel11.setText("y  precisa. Aquí podrás calcular derivadas,");
        BGTEXTjPanel.add(YPRECISAjLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 520, 50));

        PUNTOSjLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PUNTOSjLabel9.setText("puntos críticos y puntos de inflexión,");
        BGTEXTjPanel.add(PUNTOSjLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 520, 50));

        ADEMASjLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ADEMASjLabel12.setText("además de visualizar la gráfica de la función");
        BGTEXTjPanel.add(ADEMASjLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 520, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("para comprender mejor su comportamiento.");
        BGTEXTjPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1010, 50));

        BGjPanel1.add(BGTEXTjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 520, 330));

        BGToolBarjPanel1.setBackground(new java.awt.Color(42, 157, 143));
        BGToolBarjPanel1.setPreferredSize(new java.awt.Dimension(1366, 70));
        BGToolBarjPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleAppjLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        TitleAppjLabel1.setForeground(new java.awt.Color(247, 251, 252));
        TitleAppjLabel1.setText("EXPLORA EL MENÚ SUPRIOR PARA COMENZAR");
        TitleAppjLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGToolBarjPanel1.add(TitleAppjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 60));

        BGjPanel1.add(BGToolBarjPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 440, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Texto.png"))); // NOI18N
        BGjPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 530, 230));

        jPanel3.add(BGjPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BGjPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarBuscarjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarBuscarjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarBuscarjTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADEMASjLabel12;
    private javax.swing.JPanel BGBreadCrumjPanel;
    private javax.swing.JPanel BGTEXTjPanel;
    private javax.swing.JPanel BGToolBarjPanel;
    private javax.swing.JPanel BGToolBarjPanel1;
    private javax.swing.JPanel BGjPanel;
    private javax.swing.JPanel BGjPanel1;
    private javax.swing.JTextField BarBuscarjTextField;
    private javax.swing.JLabel FUNCIOESjLabel7;
    private javax.swing.JLabel PUNTOSjLabel9;
    private javax.swing.JLabel TitleAppjLabel;
    private javax.swing.JLabel TitleAppjLabel1;
    private javax.swing.JLabel UNAjLabel10;
    private javax.swing.JLabel YPRECISAjLabel11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
